# Generated by Django 4.1 on 2023-01-28 06:31

import django.contrib.postgres.fields
from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UserPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.IntegerField()),
                (
                    "image_urls",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.URLField(blank=True), default=list, size=None
                    ),
                ),
                ("post_title", models.CharField(max_length=100)),
                ("post_gist", models.CharField(max_length=250)),
                ("post_description", models.TextField(max_length=3000)),
                ("likes", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=60)),
                ("first_name", models.CharField(max_length=40)),
                ("last_name", models.CharField(max_length=40)),
                ("user_bio", models.TextField(blank=True, max_length=500)),
                (
                    "tech_stack",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=50),
                        default=list,
                        size=None,
                    ),
                ),
                ("profile_photo", models.URLField(blank=True)),
                ("email", models.EmailField(max_length=254)),
                ("dob", models.DateField()),
                ("user_gender", models.CharField(max_length=40)),
                (
                    "phone_number",
                    phonenumber_field.modelfields.PhoneNumberField(
                        max_length=128, region=None
                    ),
                ),
                ("country", models.CharField(max_length=40)),
                ("profession", models.CharField(max_length=50)),
                ("organisation", models.CharField(blank=True, max_length=200)),
                (
                    "followers",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.IntegerField(),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
            ],
        ),
    ]
