# Generated by Django 4.1.7 on 2023-04-02 03:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TechStackList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tech_name", models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_bio", models.TextField(blank=True, max_length=500)),
                ("profile_photo", models.URLField(blank=True)),
                ("dob", models.DateField(blank=True)),
                ("user_gender", models.CharField(max_length=40)),
                ("country", models.CharField(max_length=40)),
                ("profession", models.CharField(max_length=50)),
                ("organisation", models.CharField(blank=True, max_length=200)),
                (
                    "tech_stack",
                    models.ManyToManyField(blank=True, to="schedio.techstacklist"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to="")),
                ("post_title", models.CharField(max_length=100)),
                ("post_gist", models.CharField(max_length=250)),
                ("post_description", models.TextField(max_length=3000)),
                ("time_created", models.DateTimeField(auto_now_add=True)),
                ("last_edit", models.DateTimeField(auto_now=True)),
                (
                    "likes",
                    models.ManyToManyField(
                        related_name="post_like", to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "tech_stack",
                    models.ManyToManyField(
                        blank=True,
                        related_name="tech_stack",
                        to="schedio.techstacklist",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserFollowing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "following_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="followers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="follwing",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "following_user")},
            },
        ),
        migrations.CreateModel(
            name="TechStackForUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tech_name_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="schedio.techstacklist",
                    ),
                ),
                (
                    "user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="schedio.userprofile",
                    ),
                ),
            ],
            options={
                "unique_together": {("user_id", "tech_name_id")},
            },
        ),
        migrations.CreateModel(
            name="TechStackForPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "post_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="schedio.userpost",
                    ),
                ),
                (
                    "tech_name",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="schedio.techstacklist",
                    ),
                ),
            ],
            options={
                "unique_together": {("post_id", "tech_name")},
            },
        ),
        migrations.CreateModel(
            name="ImageUrlsForPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image_url", models.URLField()),
                (
                    "post_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="schedio.userpost",
                    ),
                ),
            ],
            options={
                "unique_together": {("post_id", "image_url")},
            },
        ),
    ]
