# Generated by Django 4.1 on 2023-01-23 18:43

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schedio", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.IntegerField()),
                (
                    "image_urls",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.URLField(blank=True), default=list, size=None
                    ),
                ),
                ("post_title", models.CharField(max_length=100)),
                ("post_gist", models.CharField(max_length=250)),
                ("post_description", models.TextField(max_length=3000)),
                ("likes", models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name="userprofile",
            name="profile_photo",
            field=models.URLField(default=1),
            preserve_default=False,
        ),
    ]
