# Generated by Django 4.1.7 on 2023-04-02 05:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("schedio", "0002_alter_userprofile_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="userpost",
            name="collaboraters",
            field=models.ManyToManyField(
                related_name="collaboraters", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
