# Generated by Django 4.1 on 2023-01-29 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schedio", "0002_alter_userprofile_email_alter_userprofile_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userpost",
            name="likes",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
