# Generated by Django 4.1 on 2023-02-01 08:30

import django.contrib.postgres.fields
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("schedio", "0003_alter_userpost_likes"),
    ]

    operations = [
        migrations.AddField(
            model_name="userpost",
            name="last_edit",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="userpost",
            name="tech_stack",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=50), default=list, size=None
            ),
        ),
        migrations.AddField(
            model_name="userpost",
            name="time_created",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="userpost",
            name="likes",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
