# Generated by Django 4.0.4 on 2023-02-28 13:46

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('schedio', '0004_userpost_last_edit_userpost_tech_stack_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpost',
            name='image_urls',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.URLField(blank=True), default=['https://picsum.photos/seed/picsum/800/600'], size=None),
        ),
        migrations.RemoveField(
            model_name='userpost',
            name='likes',
        ),
        migrations.AddField(
            model_name='userpost',
            name='likes',
            field=models.ManyToManyField(related_name='post_like', to=settings.AUTH_USER_MODEL),
        ),
    ]
