# Generated by Django 4.1.7 on 2023-04-03 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schedio", "0005_remove_userpost_github_remove_userpost_linkedin_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userpost",
            name="status",
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
